name = "Dex"
uuid = "90177ba7-a91c-5852-bc95-36ac82816823"
keywords = ["dex", "julia"]
license = "MIT"
desc = "Launch and manage Dex from Julia"
version = "0.5.0"

[deps]
Dex_jll = "f1ef5e10-671a-599f-ac25-3c68827556ba"

[compat]
julia = "1.3"
Dex_jll = "2.30"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[targets]
test = ["Test", "JSON", "HTTP"]
